//CHECKSTYLE:OFF
package org.vlad.awsresourcemonitor;
/* Generated by autorevision - do not hand-hack! */

public class autorevision {
  public static final String VCS_TYPE = "git";
  public static final String VCS_BASENAME = "AWSResourceMonitor";
  public static final String VCS_UUID = "d8f01732df7fe0e8bee98d0a3a64743846e3ae92";
  public static final long VCS_NUM = 13;
  public static final String VCS_DATE = "1924-04-11T12:10:09-0500";
  public static final String VCS_BRANCH = "개인 빌드";
  public static final String VCS_TAG = "v/0.1.0";
  public static final long VCS_TICK = 9;
  public static final String VCS_EXTRA = "";

  public static final String VCS_FULL_HASH = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
  public static final String VCS_SHORT_HASH = "私建";

  public static final boolean VCS_WC_MODIFIED = true;

  public static final String BUILD_URL = "Construire privée";
  public static final String BUILD_NUMBER = "99999";
  public static final String BUILD_TIME = "1950-01-01T22:05:30EST";
}

//CHECKSTYLE:ON
