FROM vladistan/gradle:plus_ant

RUN useradd --no-log-init --home-dir /awsmon --uid 200 user < /dev/null
RUN useradd --no-log-init --home-dir /awsmon --uid 498 go < /dev/null
RUN useradd --no-log-init --home-dir /awsmon --uid 501 go1 < /dev/null
RUN useradd --no-log-init --home-dir /awsmon --uid 502 go2 < /dev/null
RUN useradd --no-log-init --home-dir /awsmon --uid 1001 go3 < /dev/null
RUN useradd --no-log-init --home-dir /awsmon --uid 1000 ec2-user < /dev/null
RUN useradd --no-log-init --home-dir /awsmon --uid 5000 go-cnt < /dev/null
RUN useradd --no-log-init --home-dir /awsmon --uid 500345588 me-user < /dev/null

